ci: add test workflow
nlnwa/solrwayback-adaption pull request #19
Opened 2023-08-29 06:35 UTC by trym-b

# Motivation

Before merging to the default branch, we would want to ensure that the `dockerfile`s builds successfully.

# Drawbacks

Ideally, this workflow should be identical to
`.github/workflows/release.yml` except for the 'push: True' field and the triggers. This means that a lot of code is duplicated, which is not great.

However, this might not be a huge issue as new images are not likely to be added to this repository.

# Future work

This commit also relies on the `Dockerfile`s and `workflow`s arguments being kept in sync. This will be improved in a future commit.

2023-08-31 13:18 UTC, andrbo approved these changes

2023-08-31 13:29 UTC, maeb requested changes

2023-08-31 13:29 UTC, maeb commented on .github/workflows/main.yml
> +          password: ${{ secrets.GITHUB_TOKEN }}
No need to log in because nothing will be pushed.

2023-09-01 09:52 UTC, maeb approved these changes

2023-09-01 10:39 UTC, trym-b commented
Thanks for the reviews @andrbo and @maeb

2023-09-01 10:39 UTC, merged